<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Slider;
use Infrangible\ETrusted\Block\Widget\Reviews;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var Reviews $block */
/** @var ViewModelRegistry $viewModels */

$sliderViewModel = $viewModels->require(Slider::class);
$itemsTemplate = 'Infrangible_ETrustedHyva::widget/reviews/item.phtml';
$slider = $sliderViewModel->getSliderForItems($itemsTemplate, $block->getReviews());
$slider->setData('max_visible', 1);
$slider->setData('maybe_purged_tailwind_slide_item_classes', 'py-1 md:w-full lg:w-full xl:w-full');
?>

<div class="etrusted-reviews">
    <?= $slider->toHtml(); ?>
</div>
